### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by webbrowser11** [G1aD05/wind-os#1]
this seems to have errors running on windows except when ran in vs-code.

**Comment by G1aD05** [comment]
I run it using PyCharm

**Comment by webbrowser11** [comment]
where can i find a download-able/web version of PyCharm?

**Comment by webbrowser11** [comment]
err wait

**Comment by webbrowser11** [comment]
i'm not downloading a whole other IDE but i guess you should note it only works running in IDE terminals.

**Comment by G1aD05** [comment]
I turned on "Emulate Terminal Output" in PyCharm and that fixes it.

**Comment by webbrowser11** [comment]
OK, i will just not run it bcuz i prefer the regular command prompt and not an IDE or code editor terminal env
